version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.5.1
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Copies the Let's Encrypt certificate locally for ease of backing up
      - ./letsencrypt:/letsencrypt
       # Mounts the Traefik static configuration inside the Traefik container
      - ./traefik.dns.yml:/etc/traefik/traefik.yml
    environment:
      - "DO_AUTH_TOKEN=725861c6568880757b9a08c72b7f977756ca52d404bbefbfa1b096c9b4d112ec"

# Add the catapp service
  app:
     image: 10hith/eapp:latest
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.app.rule=Host(`excelanalysis.online`)"
       - "traefik.http.routers.app.service=app"
       - "traefik.http.services.app.loadbalancer.server.port=80"
       - "traefik.http.routers.app.entrypoints=websecure"
       - "traefik.http.routers.app.tls.certresolver=myresolver"
