services:

    app:
        image: app:latest
        restart: always
        labels:
            # Enable Traefik for this specific "backend" service
            - traefik.enable=false
            # Define the port inside of the Docker service to use
            - traefik.http.service.appName.loadbalancer.server.port=80
            # Make Traefik use this domain in HTTP ***
            - traefik.http.routers.appName-http.entrypoints=http
            - traefik.http.routers.appName-http.rule=Host(`excelanalysis.online`)
            # Use the traefik-public network (declared below)
            - traefik.docker.network=traefik-public
        networks:
            # Use the public network created to be shared between Traefik and
            # any other service that needs to be publicly available with HTTPS
            - traefik-public

networks:
    traefik-public:
        external: true